input_number = 1
output_number = 1
population = 150

hidden_activation = 'Tanh'
output_activation = 'Linear'

[mutation] 
weight_perturbation = 0.8
weight_assign = 0.1
add_connection = 0.4
remove_connection = 0.2
toggle_connection = 0.0
add_node = 0.1
remove_node = 0.1

weight_min = -1.0
weight_max = 1.0

perturb_min = -0.1
perturb_max = 0.1

[speciation]
c1 = 1.0
c2 = 0.5
compatibility_threshold = 2.0
elitism = 2

survival_rate = 0.2
stagnant_max = 20

[reproduction]
crossover_rate = 0.5