input_number = 2
output_number = 1
population = 150

hidden_activation = 'Sigmoid'
output_activation = 'Sigmoid'

[mutation] 
weight_perturbation = 0.8
weight_assign = 0.1
add_connection = 0.5
remove_connection = 0.5
toggle_connection = 0.0
add_node = 0.2
remove_node = 0.2

weight_min = -30.0
weight_max = 30.0

perturb_min = -0.5
perturb_max = 0.5

[speciation]
c1 = 1.0
c2 = 0.5
compatibility_threshold = 20.0
elitism = 5

survival_rate = 0.2

[reproduction]
crossover_rate = 0.7