name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update packages list
        run: sudo apt update
      - name: Install libasound2-dev
        run: sudo apt install libasound2-dev
      - name: Install libudev-dev
        run: sudo apt install libudev-dev
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
